"""AI code review tests; no Ollama server is required."""

from __future__ import annotations

import json
from unittest.mock import MagicMock

from roboweaver.codegen.ai_codegen import AICodeReviewer, CodeReviewResult
from roboweaver.codegen.ros2_gen import generate_ros2_package
from roboweaver.codegen.urscript_gen import generate_urscript
from roboweaver.compiler import SkillCompiler
from roboweaver.hardware.registry_robots import get_robot_spec
from roboweaver.nlu.ollama_manager import OllamaManager, OllamaResponse


def test_reviewer_returns_annotations_and_structured_issues():
    manager = MagicMock(spec=OllamaManager)
    manager.generate.side_effect = [
        OllamaResponse(
            text="```python\n# Explain the command\nprint('move')\n```",
            model="codellama:7b", latency_s=0.2,
        ),
        OllamaResponse(
            text=json.dumps({"issues": ["No timeout"], "suggestions": ["Add a timeout"]}),
            model="codellama:7b", latency_s=0.1,
        ),
    ]
    result = AICodeReviewer(manager).review_ros2("print('move')")
    assert result.annotated_code.startswith("# Explain")
    assert result.issues == ["No timeout"]
    assert result.suggestions == ["Add a timeout"]
    assert round(result.latency_s, 3) == 0.3


def test_reviewer_offline_preserves_original_code():
    manager = MagicMock(spec=OllamaManager)
    manager.generate.return_value = OllamaResponse(
        text=None, error="Ollama unreachable", model="codellama:7b",
    )
    result = AICodeReviewer(manager).review_urscript("def skill():\nend")
    assert result.original_code == "def skill():\nend"
    assert result.annotated_code is None
    assert result.error == "Ollama unreachable"


def test_generators_write_review_sidecars_without_replacing_source(tmp_path):
    skill = SkillCompiler("franka_panda").compile("Pick up the red cube", verbose=False)
    reviewer = MagicMock(spec=AICodeReviewer)
    reviewer.review_ros2.return_value = CodeReviewResult(
        original_code="original", annotated_code="# AI annotation\noriginal",
        issues=["Example issue"], model="codellama:7b",
    )
    reviewer.review_urscript.return_value = CodeReviewResult(
        original_code="original", annotated_code="# AI annotation\noriginal",
        suggestions=["Example suggestion"], model="codellama:7b",
    )

    package = generate_ros2_package(skill, tmp_path / "ros", ai_review=True, reviewer=reviewer)
    assert (package / "action_server.py").read_text().startswith("#!/usr/bin/env python3")
    assert (package / "action_server.ai_review.py").exists()
    assert json.loads((package / "ai_review.json").read_text())["issues"] == ["Example issue"]

    script = generate_urscript(
        skill, get_robot_spec("franka_panda"), tmp_path / "pick.script",
        ai_review=True, reviewer=reviewer,
    )
    assert script.read_text().startswith("# Generated by RoboWeaver")
    assert (tmp_path / "pick.ai_review.script").exists()
    assert json.loads((tmp_path / "pick.ai_review.json").read_text())["suggestions"] == ["Example suggestion"]
