"""ABB RAPID generation -- the second real target-specific CodegenBackend
dialect (RoboWeaver previously shipped only ROS 2 and URScript). Generates
syntactically valid RAPID (ABB Robotics' native robot-programming language)
exclusively from complete RoboIR, and is target-gated to verified ABB profiles.

Honesty boundary: no offline ABB RobotStudio/RAPID compiler is available to
validate against, so this module ships its own bounded structural syntax
checker (module/proc balance, statement termination, identifier form). That
checker is real but it is not RobotStudio; it does not certify the program
against a real ABB controller. See MILESTONES.md.

RAPID jointtarget axis values are degrees, not radians -- unlike URScript's
movej (radians). This module converts RoboIR's radian waypoints explicitly;
getting that wrong would silently miscommand the robot.
"""

from __future__ import annotations

import math
import re
from pathlib import Path

from roboweaver.hardware.robot_spec import RobotSpec
from roboweaver.identifiers import safe_comment, safe_identifier
from roboweaver.ir.schema import RoboIR

_MAX_RAPID_IDENTIFIER = 32
_EXTERNAL_AXES = "[9E9,9E9,9E9,9E9,9E9,9E9]"
_STRUCTURAL_KEYWORDS = {"MODULE", "ENDMODULE", "PROC", "ENDPROC"}
_IDENTIFIER_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,31}$")


def generate_abb_rapid(
    ir: RoboIR,
    robot_spec: RobotSpec,
    output_path: str | Path,
) -> Path:
    """Walk the RoboIR program in order, emitting one real RAPID statement per
    task: MOVE_TO -> MoveAbsJ per real waypoint (degrees, zone `fine` on the
    final waypoint of each segment), OPEN_GRIPPER/CLOSE_GRIPPER -> SetDO,
    WAIT -> WaitTime(<real declared duration>)."""
    if ir.program is None or ir.lowering is None:
        raise ValueError("ABB RAPID generation requires complete RoboIR program and lowering data.")
    if robot_spec.id != ir.execution.robot_id or ir.lowering.robot_id != robot_spec.id:
        raise ValueError("ABB RAPID target does not match the verified RoboIR lowering.")
    if robot_spec.dof != 6 or "abb" not in robot_spec.manufacturer.lower():
        raise ValueError(
            f"ABB RAPID backend only supports verified ABB 6-DOF targets, got {robot_spec.id}."
        )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    object_comment = safe_comment(ir.program.object_name)
    module_name = safe_identifier(
        f"roboweaver_{ir.action}_{ir.program.object_name}",
        default="roboweaver_skill",
        max_length=_MAX_RAPID_IDENTIFIER,
    )
    lines = [
        f"MODULE {module_name}",
        f"    ! Generated by RoboWeaver -- {ir.action} {object_comment}",
        f"    ! Target: {safe_comment(robot_spec.name)} ({robot_spec.dof}-DOF)",
        "    ! Joint targets are degrees; RoboIR waypoints are converted from radians.",
        "    PROC main()",
    ]

    trajectories = {
        trajectory.task_description: trajectory for trajectory in ir.lowering.trajectories
    }
    for task in ir.program.tasks:
        _emit_task(lines, task, trajectories)

    lines.append("    ENDPROC")
    lines.append("ENDMODULE")

    code = "\n".join(lines) + "\n"
    validate_rapid_syntax(code)
    out.write_text(code, encoding="utf-8")
    return out


def _emit_task(lines: list[str], task, trajectories) -> None:
    comment = safe_comment(task.description)
    if task.type == "MOVE_TO":
        segment = trajectories.get(task.description)
        if segment is None:
            lines.append(f"        ! {comment}: no motion_plan entry (see RW502) -- skipped")
            return
        lines.append(f"        ! {comment}")
        last_index = len(segment.waypoints) - 1
        for index, waypoint in enumerate(segment.waypoints):
            axes = ",".join(f"{math.degrees(value):.4f}" for value in waypoint)
            zone = "fine" if index == last_index else "z50"
            lines.append(f"        MoveAbsJ [[{axes}],{_EXTERNAL_AXES}], v200, {zone}, tool0;")
        return
    fixed = {
        "CLOSE_GRIPPER": "        SetDO doGripper, 1;",
        "OPEN_GRIPPER": "        SetDO doGripper, 0;",
    }.get(task.type)
    if fixed is not None:
        lines.extend([f"        ! {comment}", fixed])
    elif task.type == "WAIT":
        duration = float(task.parameters.get("duration", 0.5))
        lines.extend([f"        ! {comment}", f"        WaitTime {duration:.4f};"])
    elif task.type in ("PERCEIVE", "VERIFY_GRASP"):
        lines.append(f"        ! {comment} (host-side step, no RAPID equivalent)")


def _require_valid_module_name(line: str) -> None:
    name = line.split(None, 1)[1].strip()
    if not _IDENTIFIER_RE.fullmatch(name):
        raise ValueError(f"Invalid RAPID module identifier: {name!r}")


def validate_rapid_syntax(code: str) -> None:
    """Bounded structural check: MODULE/PROC balance, valid identifiers, and
    every statement line properly terminated. Not an ABB RobotStudio compile."""
    module_depth = 0
    proc_depth = 0
    for raw_line in code.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("!"):
            continue
        first_word = line.split(None, 1)[0].split("(")[0]
        if first_word == "MODULE":
            _require_valid_module_name(line)
            module_depth += 1
        elif first_word == "ENDMODULE":
            module_depth -= 1
        elif first_word.startswith("PROC"):
            proc_depth += 1
        elif first_word == "ENDPROC":
            proc_depth -= 1
        elif not line.endswith(";"):
            raise ValueError(f"RAPID statement is missing a terminating ';': {line!r}")
    if module_depth != 0:
        raise ValueError("Unbalanced MODULE/ENDMODULE in generated RAPID.")
    if proc_depth != 0:
        raise ValueError("Unbalanced PROC/ENDPROC in generated RAPID.")
