"""
RobotSpec -> URDF / STL generation.

This is RoboWeaver's 3D model generation, and it is deliberately *derived* rather
than *generated by a language model*. Everything emitted here comes from the
RobotSpec that already drives the IK solver: real joint axes, real limits, real
link lengths, real masses. That matters for three reasons:

  1. It is loadable. The output is standards-compliant URDF, so RViz, Gazebo,
     PyBullet, Isaac Sim and MoveIt all accept it directly.
  2. It is consistent with the compiler. The same numbers that produced the
     motion plan produce the model, so what you visualise is what was planned
     against -- an LLM-invented mesh would look plausible and mean nothing.
  3. It is deterministic. The same robot always yields byte-identical URDF, so
     it can be committed, diffed, and reviewed.

Link geometry is approximated as a cylinder per link. That is an honest
approximation of the kinematic chain, not a claim to be vendor CAD -- where real
CAD exists (the Franka meshes in the frontend), it should be preferred for
rendering. Inertia tensors use the exact closed form for a solid cylinder, so
they are physically consistent with the stated mass rather than made up.
"""

from __future__ import annotations

import math
import struct
from pathlib import Path
from typing import Sequence

from roboweaver.hardware.robot_spec import RobotSpec

# Rendered link radius as a fraction of link length, clamped to a sane band so
# that very short links (wrists) do not become discs and long links do not
# become needles.
_RADIUS_RATIO = 0.13
_MIN_RADIUS_M = 0.02
_MAX_RADIUS_M = 0.09


def _link_radius(length: float) -> float:
    return max(_MIN_RADIUS_M, min(_MAX_RADIUS_M, length * _RADIUS_RATIO))


def _cylinder_inertia(mass: float, radius: float, length: float) -> tuple[float, float, float]:
    """Exact inertia tensor diagonal for a solid cylinder about its centre of
    mass, with the cylinder axis along z:
        Ixx = Iyy = (1/12) m (3r^2 + h^2),  Izz = (1/2) m r^2
    """
    ixx = (1.0 / 12.0) * mass * (3.0 * radius * radius + length * length)
    izz = 0.5 * mass * radius * radius
    return ixx, ixx, izz


def _fmt(value: float) -> str:
    """Fixed precision so output is deterministic and diffable."""
    return f"{value:.6f}"


def _joint_type(spec_type: str) -> str:
    return "prismatic" if spec_type.lower().startswith("prismatic") else "revolute"


def generate_urdf(spec: RobotSpec, use_mesh_files: bool = False, mesh_dir: str = "meshes") -> str:
    """Build a complete URDF document for `spec`.

    `use_mesh_files` swaps the inline cylinder primitives for <mesh> references
    to the STL files that export_meshes() writes, for pipelines that require
    mesh assets rather than primitives.
    """
    n = spec.dof
    lines: list[str] = []
    add = lines.append

    add('<?xml version="1.0"?>')
    add(f'<!-- Generated by RoboWeaver from RobotSpec "{spec.id}". Do not hand-edit. -->')
    add(f'<!-- {spec.manufacturer} {spec.name} | {spec.dof}-DOF | '
        f'payload {spec.payload_capacity_kg} kg | reach {spec.max_reach_m} m -->')
    add(f'<robot name="{spec.id}">')

    # World-anchored base. base_height_m lifts the first joint off the floor,
    # matching the offset forward_kinematics_ndof() applies.
    add('')
    add('  <link name="base_link">')
    add('    <visual>')
    add(f'      <origin xyz="0 0 {_fmt(spec.base_height_m / 2.0)}" rpy="0 0 0"/>')
    add('      <geometry>')
    add(f'        <cylinder radius="{_fmt(max(0.05, _MAX_RADIUS_M))}" length="{_fmt(max(0.01, spec.base_height_m))}"/>')
    add('      </geometry>')
    add('      <material name="roboweaver_base">')
    add('        <color rgba="0.15 0.16 0.20 1.0"/>')
    add('      </material>')
    add('    </visual>')
    add('    <collision>')
    add(f'      <origin xyz="0 0 {_fmt(spec.base_height_m / 2.0)}" rpy="0 0 0"/>')
    add('      <geometry>')
    add(f'        <cylinder radius="{_fmt(max(0.05, _MAX_RADIUS_M))}" length="{_fmt(max(0.01, spec.base_height_m))}"/>')
    add('      </geometry>')
    add('    </collision>')
    add('    <inertial>')
    add('      <mass value="2.0"/>')
    add('      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>')
    add('    </inertial>')
    add('  </link>')

    parent = "base_link"
    for i in range(n):
        joint = spec.joints[i]
        link = spec.links[i] if i < len(spec.links) else None
        length = link.length if link else 0.15
        mass = link.mass if link else 1.0
        radius = _link_radius(length)
        link_name = f"{spec.id}_link{i + 1}"

        ax, ay, az = joint.axis
        # The first joint sits at the top of the base; every later joint sits at
        # the far end of its parent link -- the same chain the FK composes.
        offset_z = spec.base_height_m if i == 0 else (spec.links[i - 1].length if i - 1 < len(spec.links) else 0.15)

        add('')
        add(f'  <joint name="{joint.name}" type="{_joint_type(joint.type)}">')
        add(f'    <parent link="{parent}"/>')
        add(f'    <child link="{link_name}"/>')
        add(f'    <origin xyz="0 0 {_fmt(offset_z)}" rpy="0 0 0"/>')
        add(f'    <axis xyz="{_fmt(ax)} {_fmt(ay)} {_fmt(az)}"/>')
        add(f'    <limit lower="{_fmt(joint.lower_limit)}" upper="{_fmt(joint.upper_limit)}" '
            f'effort="{_fmt(joint.max_effort)}" velocity="{_fmt(joint.max_velocity)}"/>')
        # Mild damping keeps Gazebo stable; it is a simulation aid, not a
        # measured property of the real hardware.
        add('    <dynamics damping="0.1" friction="0.0"/>')
        add('  </joint>')

        ixx, iyy, izz = _cylinder_inertia(mass, radius, length)
        com = link.center_of_mass if link else (0.0, 0.0, length / 2.0)
        com_z = com[2] if any(com) else length / 2.0

        add('')
        add(f'  <link name="{link_name}">')
        add('    <visual>')
        add(f'      <origin xyz="0 0 {_fmt(length / 2.0)}" rpy="0 0 0"/>')
        add('      <geometry>')
        if use_mesh_files:
            add(f'        <mesh filename="{mesh_dir}/{link_name}.stl"/>')
        else:
            add(f'        <cylinder radius="{_fmt(radius)}" length="{_fmt(length)}"/>')
        add('      </geometry>')
        add(f'      <material name="roboweaver_link{i + 1}">')
        add(f'        <color rgba="{_link_colour(i, n)}"/>')
        add('      </material>')
        add('    </visual>')
        add('    <collision>')
        add(f'      <origin xyz="0 0 {_fmt(length / 2.0)}" rpy="0 0 0"/>')
        add('      <geometry>')
        add(f'        <cylinder radius="{_fmt(radius)}" length="{_fmt(length)}"/>')
        add('      </geometry>')
        add('    </collision>')
        add('    <inertial>')
        add(f'      <origin xyz="{_fmt(com[0])} {_fmt(com[1])} {_fmt(com_z)}" rpy="0 0 0"/>')
        add(f'      <mass value="{_fmt(mass)}"/>')
        add(f'      <inertia ixx="{_fmt(ixx)}" ixy="0" ixz="0" '
            f'iyy="{_fmt(iyy)}" iyz="0" izz="{_fmt(izz)}"/>')
        add('    </inertial>')
        add('  </link>')

        parent = link_name

    # Tool frame: a zero-mass fixed link marking the end-effector origin, which
    # is what the IK solver actually drives.
    last_len = spec.links[n - 1].length if n - 1 < len(spec.links) else 0.15
    add('')
    add(f'  <joint name="{spec.id}_tool_joint" type="fixed">')
    add(f'    <parent link="{parent}"/>')
    add(f'    <child link="{spec.id}_tool0"/>')
    add(f'    <origin xyz="0 0 {_fmt(last_len)}" rpy="0 0 0"/>')
    add('  </joint>')
    add('')
    add(f'  <link name="{spec.id}_tool0"/>')
    add('')
    add('</robot>')
    return "\n".join(lines) + "\n"


def _link_colour(index: int, total: int) -> str:
    """Cyan -> violet ramp along the chain, so joint order is readable at a glance."""
    t = index / max(1, total - 1)
    r = 0.13 + t * (0.55 - 0.13)
    g = 0.83 + t * (0.36 - 0.83)
    b = 0.93 + t * (0.96 - 0.93)
    return f"{r:.3f} {g:.3f} {b:.3f} 1.0"


# ── Procedural mesh generation ────────────────────────────────────────

def _cylinder_triangles(
    radius: float, length: float, segments: int = 24
) -> list[tuple[tuple[float, float, float], ...]]:
    """Tessellate a capped cylinder into triangles, axis along +z from z=0."""
    tris: list[tuple[tuple[float, float, float], ...]] = []
    ring = [
        (radius * math.cos(2 * math.pi * i / segments), radius * math.sin(2 * math.pi * i / segments))
        for i in range(segments)
    ]

    for i in range(segments):
        x0, y0 = ring[i]
        x1, y1 = ring[(i + 1) % segments]
        b0 = (x0, y0, 0.0)
        b1 = (x1, y1, 0.0)
        t0 = (x0, y0, length)
        t1 = (x1, y1, length)
        # Side wall (two triangles per segment)
        tris.append((b0, b1, t1))
        tris.append((b0, t1, t0))
        # Caps
        tris.append(((0.0, 0.0, 0.0), b1, b0))
        tris.append(((0.0, 0.0, length), t0, t1))
    return tris


def _triangle_normal(tri: Sequence[tuple[float, float, float]]) -> tuple[float, float, float]:
    (ax, ay, az), (bx, by, bz), (cx, cy, cz) = tri[0], tri[1], tri[2]
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    mag = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return nx / mag, ny / mag, nz / mag


def generate_link_stl(radius: float, length: float, segments: int = 24) -> bytes:
    """Binary STL for one link. Binary rather than ASCII because these load an
    order of magnitude faster in RViz/Gazebo and are a fraction of the size."""
    tris = _cylinder_triangles(radius, length, segments)
    buf = bytearray()
    buf.extend(b"RoboWeaver procedural link mesh".ljust(80, b"\0"))
    buf.extend(struct.pack("<I", len(tris)))
    for tri in tris:
        nx, ny, nz = _triangle_normal(tri)
        buf.extend(struct.pack("<3f", nx, ny, nz))
        for vx, vy, vz in tri:
            buf.extend(struct.pack("<3f", vx, vy, vz))
        buf.extend(struct.pack("<H", 0))
    return bytes(buf)


def export_meshes(spec: RobotSpec, mesh_dir: str | Path) -> list[Path]:
    """Write one STL per link. Returns the paths actually written."""
    out_dir = Path(mesh_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for i in range(spec.dof):
        link = spec.links[i] if i < len(spec.links) else None
        length = link.length if link else 0.15
        path = out_dir / f"{spec.id}_link{i + 1}.stl"
        path.write_bytes(generate_link_stl(_link_radius(length), length))
        written.append(path)
    return written


def export_urdf(
    spec: RobotSpec,
    output_path: str | Path,
    with_meshes: bool = False,
) -> tuple[Path, list[Path]]:
    """Write the URDF (and optionally STL meshes beside it).

    Returns (urdf_path, mesh_paths).
    """
    urdf_path = Path(output_path)
    urdf_path.parent.mkdir(parents=True, exist_ok=True)

    meshes: list[Path] = []
    if with_meshes:
        meshes = export_meshes(spec, urdf_path.parent / "meshes")

    urdf_path.write_text(generate_urdf(spec, use_mesh_files=with_meshes), encoding="utf-8")
    return urdf_path, meshes
