"""
URScript generation -- one real CodegenBackend target (docs/COMPILER_ROADMAP.md v2
vision, item 3). Generates real, syntactically valid URScript (Universal Robots'
native robot-programming language) exclusively from complete RoboIR.

The backend refuses non-Universal-Robots targets. Syntactically plausible URScript
for another manufacturer is not a useful or safe deployment artifact.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from roboweaver.hardware.robot_spec import RobotSpec
from roboweaver.identifiers import safe_comment, safe_identifier
from roboweaver.ir.schema import RoboIR

if TYPE_CHECKING:
    from roboweaver.codegen.ai_codegen import AICodeReviewer


def generate_urscript(
    ir: RoboIR,
    robot_spec: RobotSpec,
    output_path: str | Path,
    ai_review: bool = False,
    reviewer: "AICodeReviewer | None" = None,
) -> Path:
    """Walk the RoboIR program in order, emitting one real URScript
    statement per task: MOVE_TO -> movej() per real waypoint (spaced by that
    segment's real per-step duration), OPEN_GRIPPER/CLOSE_GRIPPER ->
    set_digital_out(), WAIT -> sleep(<real declared duration>)."""
    if ir.program is None or ir.lowering is None:
        raise ValueError("URScript generation requires complete RoboIR program and lowering data.")
    if robot_spec.id != ir.execution.robot_id or ir.lowering.robot_id != robot_spec.id:
        raise ValueError("URScript target does not match the verified RoboIR lowering.")
    if robot_spec.dof != 6 or "universal robots" not in robot_spec.manufacturer.lower():
        raise ValueError(
            f"URScript backend only supports verified Universal Robots 6-DOF targets, got {robot_spec.id}."
        )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    object_comment = safe_comment(ir.program.object_name)
    program_name = safe_identifier(
        f"roboweaver_{ir.action}_{ir.program.object_name}",
        default="roboweaver_skill",
    )
    lines = [
        f"# Generated by RoboWeaver -- {ir.action} {object_comment}",
        f"# Target: {safe_comment(robot_spec.name)} ({robot_spec.dof}-DOF)",
        f"def {program_name}():",
    ]

    trajectories = {
        trajectory.task_description: trajectory for trajectory in ir.lowering.trajectories
    }
    for task in ir.program.tasks:
        _emit_task(lines, task, trajectories)

    lines.append("end")
    lines.append("")
    lines.append(f"{program_name}()")

    code = "\n".join(lines) + "\n"
    out.write_text(code, encoding="utf-8")
    if ai_review:
        _write_ai_review(code, out, ir, robot_spec, reviewer)
    return out


def _emit_task(lines: list[str], task, trajectories) -> None:
    comment = safe_comment(task.description)
    if task.type == "MOVE_TO":
        segment = trajectories.get(task.description)
        if segment is None:
            lines.append(f"  # {comment}: no motion_plan entry (see RW502) -- skipped")
            return
        count = len(segment.waypoints)
        step_time = (
            segment.duration_s / (count - 1)
            if count > 1 and segment.duration_s > 0 else 0.0
        )
        lines.append(f"  # {comment}")
        for waypoint in segment.waypoints:
            joints = ", ".join(f"{value:.6f}" for value in waypoint)
            lines.append(f"  movej([{joints}], a=1.4, v=1.05, t={step_time:.4f}, r=0.0)")
        return
    fixed = {
        "CLOSE_GRIPPER": "  set_digital_out(0, True)",
        "OPEN_GRIPPER": "  set_digital_out(0, False)",
    }.get(task.type)
    if fixed is not None:
        lines.extend([f"  # {comment}", fixed])
    elif task.type == "WAIT":
        duration = float(task.parameters.get("duration", 0.5))
        lines.extend([f"  # {comment}", f"  sleep({duration:.4f})"])
    elif task.type in ("PERCEIVE", "VERIFY_GRASP"):
        lines.append(f"  # {comment} (host-side step, no URScript equivalent)")


def _write_ai_review(code: str, out: Path, ir: RoboIR, robot_spec: RobotSpec, reviewer) -> None:
    if reviewer is None:
        from roboweaver.codegen.ai_codegen import AICodeReviewer
        reviewer = AICodeReviewer()
    review = reviewer.review_urscript(
        code, robot_id=robot_spec.id, action=ir.action,
        object_name=ir.program.object_name, dof=robot_spec.dof,
    )
    annotated_path = out.with_name(f"{out.stem}.ai_review{out.suffix}")
    if review.annotated_code:
        annotated_path.write_text(review.annotated_code.rstrip() + "\n", encoding="utf-8")
    out.with_name(f"{out.stem}.ai_review.json").write_text(
        json.dumps({
            "model": review.model, "latency_s": review.latency_s,
            "issues": review.issues, "suggestions": review.suggestions,
            "error": review.error,
            "annotated_file": annotated_path.name if review.annotated_code else None,
        }, indent=2) + "\n",
        encoding="utf-8",
    )
