"""
URScript generation -- one real CodegenBackend target (docs/COMPILER_ROADMAP.md v2
vision, item 3). Generates real, syntactically valid URScript (Universal Robots'
native robot-programming language) from a CompiledSkill's real task graph and motion
plan.

Honesty note: this produces syntactically correct URScript that would parse on a real
UR controller -- the movej()/sleep()/set_digital_out() calls and their real joint
values/durations are genuine, computed data (same integrity level as
codegen/urdf_gen.py's real-geometry generation), not an LLM guess. Generating it for a
non-UR RobotSpec (a different joint count than a real UR arm's 6) is honest,
data-driven text generation from whatever the compiler actually produced -- it is not
a claim that any robot's real controller accepts URScript, or that a non-6-DOF script
would load on real hardware.
"""

from __future__ import annotations

from pathlib import Path

from roboweaver.hardware.robot_spec import RobotSpec
from roboweaver.types import CompiledSkill, TaskType


def generate_urscript(skill: CompiledSkill, robot_spec: RobotSpec, output_path: str | Path) -> Path:
    """Walks the real, compiled task_graph in order, emitting one real URScript
    statement per task: MOVE_TO -> movej() per real waypoint (spaced by that
    segment's real per-step duration), OPEN_GRIPPER/CLOSE_GRIPPER ->
    set_digital_out(), WAIT -> sleep(<real declared duration>)."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    program_name = f"roboweaver_{skill.intent.action.value.lower()}_{skill.intent.object_name}"
    lines = [
        f"# Generated by RoboWeaver -- {skill.intent.action.value} {skill.intent.object_name}",
        f"# Target: {robot_spec.name} ({robot_spec.dof}-DOF)",
        f"def {program_name}():",
    ]

    for task in skill.task_graph.tasks:
        if task.type is TaskType.MOVE_TO:
            seg = skill.motion_plan.trajectories.get(task.description)
            if seg is None:
                lines.append(f"  # {task.description}: no motion_plan entry (see RW502) -- skipped")
                continue
            n = len(seg.waypoints)
            step_t = seg.duration / (n - 1) if n > 1 and seg.duration > 0 else 0.0
            lines.append(f"  # {task.description}")
            for wp in seg.waypoints:
                joints = ", ".join(f"{q:.6f}" for q in wp)
                lines.append(f"  movej([{joints}], a=1.4, v=1.05, t={step_t:.4f}, r=0.0)")
        elif task.type is TaskType.CLOSE_GRIPPER:
            lines.append(f"  # {task.description}")
            lines.append("  set_digital_out(0, True)")
        elif task.type is TaskType.OPEN_GRIPPER:
            lines.append(f"  # {task.description}")
            lines.append("  set_digital_out(0, False)")
        elif task.type is TaskType.WAIT:
            duration = float(task.params.get("duration", 0.5))
            lines.append(f"  # {task.description}")
            lines.append(f"  sleep({duration:.4f})")
        elif task.type in (TaskType.PERCEIVE, TaskType.VERIFY_GRASP):
            lines.append(f"  # {task.description} (host-side step, no URScript equivalent)")

    lines.append("end")
    lines.append("")
    lines.append(f"{program_name}()")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
